shellcheck SC2086: double quote to prevent globbing and word splitting

diff --git a/msvs-promote-path b/msvs-promote-path
--- a/msvs-promote-path
+++ b/msvs-promote-path
@@ -43,7 +43,7 @@ do
     T="$i"
     FIRST=0
   else
-    if [ $FOUND -eq 0 ] && [ -x $i/link ] && [ "$($i/link --version 2>/dev/null | sed -ne "1s/Microsoft (R) Incremental Linker//p")" != "" ] ; then
+    if [ $FOUND -eq 0 ] && [ -x "$i/link" ] && [ "$("$i/link" --version 2>/dev/null | sed -ne "1s/Microsoft (R) Incremental Linker//p")" != "" ] ; then
       FOUND=1
       T="$i:$T"
       PROM=$i
@@ -55,9 +55,9 @@ done
 unset IFS
 
 if [ $FOUND -eq 0 ] ; then
-  echo The Microsoft Linker was not found in any of the PATH entries!>&2
+  echo "The Microsoft Linker was not found in any of the PATH entries!">&2
   exit 1
 else
   echo "$PROM moved to the front of \$PATH">&2
-  echo export PATH=\"$T\"
+  echo "export PATH=\"$T\""
 fi
